name: components
channels:
  - conda-forge
  - defaults
dependencies:
  - pyyaml=5.3.1
  - hydra-core=1.0.6
  - pip=20.3.3
  - scikit-learn=0.24.1
  - pip:
      - mlflow==2.8.1
      - wandb==0.13.9
