name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.15
  - hydra-core=1.0.6
  - matplotlib=3.6.2
  - pandas=1.2.3
  - jupyterlab=3.0.12
  - pip=23.3.1
  - mlflow==2.1.1
  - pip:
      - wandb==0.13.9