name: basic_cleaning
channels:
  - conda-forge
  - defaults
dependencies:
  - hydra-core=1.3.2
  - matplotlib=3.6.2
  - pandas=1.1.4
  - pip=20.3.3
  - scikit-learn=0.24.1
  - pip:
      - mlflow==2.1.1
      - wandb==0.13.9
